### ISSUE TITLE
Deep Freeze causing bug

### ISSUE THREAD

**Issue by Wickett22** [Calemi/ChristmasSpirit-1.16.4#7]
Deep Freeze causing bug making entities both hostile and non move very slow. it could be a mod conflict but there is not a config option in the CS mod to remove this feature.

**Comment by mother-frog** [comment]
the same thing is happening to me except i have the config for biome editer turned off so idk why

**Comment by Calemi** [comment]
I'll do some more troubleshooting, but I believe I fixed this issue last year? Have both of you encountered this on the forge version?
