### ISSUE TITLE
Slows entity speeds

### ISSUE THREAD

**Issue by mother-frog** [Calemi/ChristmasSpirit-1.16.4#8]
Hi! I put this on my 1.18 server and upon addition it reduced speed of all entities, I removed it and it went away so I think it is something to do with the mod, my tps is good as well for further assurance. Is there a fix for this?

**Comment by Calemi** [comment]
1.18? Are you sure you running the Forge version? If you are on fabric, use https://github.com/frqnny/ChristmasSpirit/issues. If not, I can't seem to recreate the issue.

**Comment by frqnny** [comment]
hahaha this is my issue yes this is fixed in latest release sorry calemi for bothering you.

**Comment by Calemi** [comment]
It's all good lol!
